### PR TITLE
Fixed: RHS Compatibility - Remove scope adjust from ACOG Scopes

### LINKED ISSUE #7055: RHS ACOGs can be adjusted like sniper scope.
Arma 3 Version: 1.94 (stable )
CBA Version: 3.11.2.190515-cec0e465
ACE3 Version: 3.12.6.43-7d9a4f47

Mods:
--All 4 RHS mods + 3 lastest offical ACE compats
--CBA_A3
--ace 

Discription:
All the ACOGs from RHS can be adjusted  horizontally and vertically in mils, is it intentionally?
On the contrary，RHS Spectre DR scopes do not have this feature.

Image:
https://imgchr.com/i/V7G53d

### PR DESCRIPTION
**Pull request by dedmen**
Fixes #7055

### CODE REVIEW

File: optionals/compat_rhs_usf3/CfgWeapons.hpp [hunk 1]
```diff
@@ -156,6 +156,13 @@ class CfgWeapons {
             };
         };
     };
+    //For some reason ACOG is a sniper scope, but we don't want scope adjust
```
Comment (jonpas) [inline optionals/compat_rhs_usf3/CfgWeapons.hpp]:
```suggestion
    // ACOG is a sniper scope for some reason, but we don't want scope adjust
```

**Comment by CCRcmcpe** [comment]
It should be adjustable according to [ACOG's Operator Manual](https://github.com/acemod/ACE3/files/7833990/A1j5Y2GYQVS.pdf).
