### PR TITLE
Compat RHS - Fix explosives compat

### LINKED ISSUE #9564: RHS explosives vs ACE 3.16.0
Arma 3: 2.14.150957 stable
CBA_A3 v3.16.0.231017 stable
ACE3: 3.16.0 stable

RHSUSAF 0.5.6
RHSGREF 0.5.6
RHSSAF 0.5.6
RHSAFRF 0.5.6

Description:
Can't use/place down the following explosive devices from RHS mod (the explosive's model not show in the soldier's hand):

rhsusf_mine_m14_mag
rhsusf_mine_m49a1_10m_mag
rhsusf_mine_m49a1_3m_mag
rhsusf_mine_m49a1_6m_mag
rhs_mine_M19_mag

rhssaf_mine_mrud_c_mag
rhssaf_mine_mrud_a_mag
rhssaf_mine_mrud_b_mag
rhssaf_mine_mrud_d_mag
rhssaf_mine_pma3_mag
rhssaf_tm100_mag
rhssaf_tm200_mag
rhssaf_tm500_mag
rhssaf_mine_tma4_mag

 
[Complete list of tested explosives](https://docs.google.com/spreadsheets/d/1800gIj3eMupm8T8qaWSM9ILijzefYgM3okqbyfKEm9g/edit?usp=sharing)

Steps to reproduce:
1. Pick up explosive from a crate or Arsenal
2. Try to place down explosive from ACE menu (Explosives - Place - Explosive)
3. Listed explosives model not show in soldier's hand, and can't place down

Expected behavior:
Place down the selected explosive

Where did the issue occur?
Editor, Dedicated

### PR DESCRIPTION
**Pull request by LinkIsGrim**
**When merged this pull request will:**
- Title.
- Close #9564

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

File: addons/compat_rhs_usf3/compat_rhs_usf3_explosives/CfgMagazines.hpp [hunk 1]
```diff
@@ -24,7 +24,8 @@ class CfgMagazines {
 
     class ATMine_Range_Mag;
     class rhs_mine_M19_mag: ATMine_Range_Mag {
-        EGVAR(explosives,setupObject) = QEGVAR(explosives,Place_rhsusf_explosive_mine_M19);
+        "ace_explosives_Place_rhsusf_mine_M19"
```
Comment (PabstMirror) [inline addons/compat_rhs_usf3/compat_rhs_usf3_explosives/CfgMagazines.hpp:27]:
```suggestion
```

**Comment by LinkIsGrim** [comment]
Tested everything else, it was just those.

**Review by PabstMirror — APPROVED** [review]

**Review by LinkIsGrim — COMMENTED** [review]
Nice.
