### PR TITLE
Use correct TransportX type for ace items

### LINKED ISSUE #5068: ACE-modified crates have mismatched TransportX and cfgX types
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1` (stable)
**ACE3 Version:** `3.9.1` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
For crates like Box_NATO_Grenades_F, Box_East_Grenades_F etc, they include ACE_HandFlare_Red, ACE_HandFlare_Yellow, ACE_M84 in the TransportItems list. However, these items all exist in cfgMagazines rather than cfgWeapons (where TransportItems are normally pulled from).

General pattern that should be used: things that are listed in TransportWeapons or TransportItems exist within cfgWeapons, things that are listed in TransportMagazines exist within cfgMagazines, and things that are listed in TransportBackpacks exist within cfgVehicles.

Encountered this while producing a script, so these are only the ones that I encountered - others may exist.

**Steps to reproduce:**
- Open ConfigViewer
- Navigate to cfgVehicles
- Find an ACE-modified crate, such as Box_Nato_Grenades_F
- Inspect its TransportItems list
- Check if all items exist in cfgWeapons
- Inspect its TransportMagazines list
- Check if all items exist in cfgMagazines
- etc.

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix #5068

As far as I can tell arma can handle the wrong entries.
This does seem to put he mine detectors at the top of the "misc items" box, but I noticed no other changes.

### CODE REVIEW

File: addons/grenades/CfgVehicles.hpp [hunk 1]
```diff
@@ -2,40 +2,40 @@
...
     };
 
     class EAST_Box_Base;
     class Box_East_Grenades_F: EAST_Box_Base {
-        class TransportItems {
-            MACRO_ADDITEM(ACE_HandFlare_Yellow,12);
-            MACRO_ADDITEM(ACE_HandFlare_Red,12);
-            MACRO_ADDITEM(ACE_M84,12);
+        class TransportMagazines {
+            MACRO_ADDMAGAZINE(ACE_HandFlare_White,12);
```
Comment (SilentSpike) [inline addons/grenades/CfgVehicles.hpp]: Were these intentionally changed to white and green?

File: addons/grenades/CfgVehicles.hpp [hunk 2]
```diff
@@ -2,40 +2,40 @@
...
     };
 
     class IND_Box_Base;
     class Box_IND_Grenades_F: IND_Box_Base {
-        class TransportItems {
-            MACRO_ADDITEM(ACE_HandFlare_Yellow,12);
-            MACRO_ADDITEM(ACE_HandFlare_Green,12);
-            MACRO_ADDITEM(ACE_M84,12);
+        class TransportMagazines {
+            MACRO_ADDMAGAZINE(ACE_HandFlare_White,12);
```
Comment (SilentSpike) [inline addons/grenades/CfgVehicles.hpp]: Similar here

File: addons/grenades/CfgVehicles.hpp (hunk 1 above)
Comment (PabstMirror) [inline addons/grenades/CfgVehicles.hpp]: No I had just copied the top set, thanks for catching

**Comment by commy2** [comment]
lgtm, but what was the point again?

**Comment by PabstMirror** [comment]
I dunno, #5068 said it broke a script

**Comment by SilentSpike** [comment]
Think it's for consistency with vanilla
