### PR TITLE
Compat CUP Units - Goggles Compatibility

### LINKED ISSUE #10054: CUP goggles not working with ACE Goggles Addon.
**Mods (complete and add to the following information):**
- **Arma 3:** `2.16` LATEST STABLE
- **CBA:** `3.17.1` LATEST STABLE
- **ACE3:** `3.17.1` LATEST STABLE
- **CUP Weapons** `1.18.1` LATEST STABLE
- **CUP Units** `1.18.1` LATEST STABLE

**Description:**
CUP goggles not working with the Goggles addon. No rain effects.

**Steps to reproduce:**
Test with these CUP glasses:

CUP_G_Oakleys_clr
CUP_G_ESS_BLK_Ember

actually test with any CUP glasses / goggles

**Expected behavior:**
No rain effects when raining.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

### PR DESCRIPTION
**Pull request by Mike-MF**
**When merged this pull request will:**
- Adds ACE Goggles compatibility to CUP facewear.
- Resolves #10054

### CODE REVIEW

File: addons/compat_cup_units/CfgGlasses.hpp [hunk 1]
```diff
@@ -0,0 +1,492 @@
...
+    class CUP_G_Beard_Shades_Black: None {
+        ace_resistance = 1;
+        ace_tintAmount = 8;
+    };
+    class CUP_G_Beard_Shades_Blonde: CUP_G_Beard_Shades_Black {
+        ace_resistance = 1;
+        ace_tintAmount = 8;
+    };
+
+    // Shades - Clear
```
Comment (rautamiekka) [inline addons/compat_cup_units/CfgGlasses.hpp:378]: How come no inheritance is used for the diff variants ? These shades being a good place to, for ex, which would decrease space wasting.

Comment (jonpas) [reply addons/compat_cup_units/CfgGlasses.hpp:378]: Ask CUP, it is how they encoded it.

**Review by jonpas — APPROVED** [review]

File: addons/compat_cup_units/CfgGlasses.hpp (hunk 1 above)
Comment (rautamiekka) [reply addons/compat_cup_units/CfgGlasses.hpp:378]: This is only related to ACE, that's why.
