### PR TITLE
Aircraft - Restore missing laser designator on Commanche

### LINKED ISSUE #7712: Missing laser designator on Commanche/Blackfoot
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98`
- **CBA:** `3.15.1` 
- **ACE3:** `3.13.2`
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_
Done

**Description:**
Since Tanks DLC the Blackfoot/Comanche has a laser designator.  
With ACE it loses this, and will only have an ldag if ACE Hellfires are loaded.

**Steps to reproduce:**
- Go to Eden editor
- Spawn a Comanche with vanilla weapons, set player as gunner, start mission
- Cycle through weapons, note that ldag is missing

**Expected behavior:**
The comanche should have a laser designator, regardless of if ACE Hellfires are carried

**Where did the issue occur?**
- Editor (Singleplayer)

### PR DESCRIPTION
**Pull request by PabstMirror**
This now matches vanilla
Close #7712

### CODE REVIEW

File: addons/aircraft/Heli_Attack_01_base_F.hpp [hunk 1]
```diff
@@ -119,8 +119,8 @@ class Heli_Attack_01_base_F: Helicopter_Base_F {
 class Heli_Attack_01_dynamicLoadout_base_F: Heli_Attack_01_base_F {
     class Turrets: Turrets {
         class MainTurret: MainTurret {
-            weapons[] = {"ACE_gatling_20mm_Comanche"};
-            magazines[] = {"ACE_500Rnd_20mm_shells_Comanche"};
+            weapons[] = {"ACE_gatling_20mm_Comanche","Laserdesignator_mounted"};
```
Comment (mharis001) [inline addons/aircraft/Heli_Attack_01_base_F.hpp:122]:
```suggestion
            weapons[] = {"ACE_gatling_20mm_Comanche", "Laserdesignator_mounted"};
```

File: addons/aircraft/Heli_Attack_01_base_F.hpp [hunk 2]
```diff
@@ -119,8 +119,8 @@ class Heli_Attack_01_base_F: Helicopter_Base_F {
...
+            magazines[] = {"ACE_500Rnd_20mm_shells_Comanche","Laserbatteries"};
```
Comment (mharis001) [inline addons/aircraft/Heli_Attack_01_base_F.hpp:123]:
```suggestion
            magazines[] = {"ACE_500Rnd_20mm_shells_Comanche", "Laserbatteries"};
```
