### PR TITLE
Overpressure cleanup and fix distance check

### LINKED ISSUE #3156: FFV backblast seems too much
ACE3 Version: 3.4.2
Arma 3 Version: 1.54

**Mods:**
* `@CBA_A3`
* `@ace` 

**Placed ACE3 Modules:**
None

**Description:**
Backblast seems too much when firing a launcher FFV turned out position. Particularly in the offroad.

Video: https://www.youtube.com/watch?v=1IJt2bTD5xo&feature=youtu.be

From a realism point of view I spoke to a military buddy of mine and whilst he advices against firing from a vehicle he said it is unlikely in the video below that the firer would be wounded from the backblast. He also mentioned that if the launcher has fins (i.e. AT4) they might expand and collide with the cabin though that is a different issue.

**Steps to reproduce:**
Get an RPG-42 and get into the back seat of an offroad, turnout, select the RPG and fire.

### PR DESCRIPTION
**Pull request by PabstMirror**
- Cleanup, headers, modern privates
 - Fix #3156 (`lineIntersectsSurfaces` did not filter ffv shooter)
 - Added both a3 tank weapons, I am unsure why there were not already added.

### CODE REVIEW

File: addons/overpressure/CfgEventHandlers.hpp [hunk 1]
```diff
@@ -14,7 +14,7 @@ class Extended_PostInit_EventHandlers {
 class Extended_FiredBIS_EventHandlers {
     class CAManBase {
         class ADDON {
-            firedBIS = QUOTE(if (local (_this select 0)) then {_this call FUNC(firedEHBB);};);
+            clientFiredBIS = QUOTE(_this call FUNC(firedEHBB););
```
Comment (jokoho48) [inline addons/overpressure/CfgEventHandlers.hpp]: ? not sure but if i remeber right is clentFiredBIS only disalbed on server and not local

File: addons/overpressure/functions/fnc_cacheOverPressureValues.sqf [hunk 2]
```diff
@@ -9,68 +9,49 @@
...
+private _return = [
     (getNumber (_config >> QGVAR(angle))),
     (getNumber (_config >> QGVAR(range))),
     (getNumber (_config >> QGVAR(damage)))
 ];
-TRACE_1("Return",_return);
-_varName = format [QGVAR(values%1%2%3), _weapon, _ammo, _magazine];
+TRACE_2("Return",_varName,_return);
+
+private _varName = format [QGVAR(values%1%2%3), _weapon, _ammo, _magazine];
```
Comment (jokoho48) [inline addons/overpressure/functions/fnc_cacheOverPressureValues.sqf]: this make 0 sense

File: addons/overpressure/CfgEventHandlers.hpp (hunk 1 above)
Comment (PabstMirror) [inline addons/overpressure/CfgEventHandlers.hpp]: I switched the `if !([_firer] call EFUNC(common,isPlayer)) exitWith {};` in fireLauncherBackblast
to `_firer != ACE_player` in firedEHBB  
(because local + isPlayer could only ever be `ace_player`... I think?)

In testing re-adding the local check in the EH is slightly faster than always doing the params and `_firer != ACE_player` check when non players are shooting, so I will leave as it was.

File: addons/overpressure/functions/fnc_cacheOverPressureValues.sqf [hunk 3]
```diff
@@ -9,68 +9,49 @@
...
+private _return = [
     (getNumber (_config >> QGVAR(angle))),
     (getNumber (_config >> QGVAR(range))),
     (getNumber (_config >> QGVAR(damage)))
 ];
-TRACE_1("Return",_return);
-_varName = format [QGVAR(values%1%2%3), _weapon, _ammo, _magazine];
+
+private _varName = format [QGVAR(values%1%2%3), _weapon, _ammo, _magazine];
 missionNameSpace setVariable [format [QGVAR(values%1%2%3), _weapon, _ammo, _magazine], _return];
```
Comment (jokoho48) [inline addons/overpressure/functions/fnc_cacheOverPressureValues.sqf]: if you want to keep the var _varName than replace it in this line

**Comment by esteldunedain** [comment]
:+1:

**Comment by jokoho48** [comment]
:+1:

File: addons/overpressure/CfgEventHandlers.hpp [hunk 4]
```diff
@@ -14,7 +14,7 @@ class Extended_PostInit_EventHandlers {
 class Extended_FiredBIS_EventHandlers {
     class CAManBase {
         class ADDON {
-            firedBIS = QUOTE(if (local (_this select 0)) then {_this call FUNC(firedEHBB);};);
+            clientFiredBIS = QUOTE(if (local (_this select 0)) then {_this call FUNC(firedEHBB);};);
```
Comment (commy2) [inline addons/overpressure/CfgEventHandlers.hpp]: That would mean that there no longer is backblast on dedicated server AIs?

Comment (PabstMirror) [inline addons/overpressure/CfgEventHandlers.hpp]: We already only ran on local and isPlayer which I just switched to == ace_player.  I think the idea was that AI have no idea how backblast works, so they would not know how to use it.

The firer will still trigger the targetEvent to everyone, so player shots will still effect AI. So skipping dedi on the event is just a very small performance savings.

Comment (esteldunedain) [inline addons/overpressure/CfgEventHandlers.hpp]: :+1:
