### PR TITLE
RHS Compats - Update allowSwapBarrels for some guns

### LINKED ISSUE #6653: allow barrel swap for ACE/RHS compatibility missing
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.9.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHSAFRF
- ACE Compat - RHS Armed Forces of the Russian Federation
```

**Description:**
- MGs that should have quick-change barrels do not have the swap barrel option. It is not present in the config either.

This is also true for:
1. M249 (rhs_weap_M249_base is configured properly, however rhs_weap_m249 inherits from rhs_weap_saw_base which lacks the entry.)
2. MG42 (the ace_overheat entries are in rhs_weap_mg42_base, but ace_overheating_allowSwapBarrel is missing on it and child configs).
3. PKM (this inherits from the rhs_weap_pkp weapon, and the PKP does not have a quick change barrel, however the PK and PKM does, ergo the entry is missing from rhs_weap_pkm.)
4. M84 (same deal as the PKM, the entries for ace_overheat are from Rifle_Long_Base_F and Rifle, but the M84 is just a PKM with a solid wooden stock.)
5. FN Minimi Para RIS (and those like it. it also inherits from rhs_weap_saw_base and thusly lacks a quick-change barrel, when in reality to my knowledge all FN Minimi derivatives have quick-change barrels.

**Recommendation**
1. add ace_overheating_allowSwapBarrel = 1; in class: rhs_weap_saw_base in the config patch for USAF
2. add ace_overheating_allowSwapBarrel = 1; in class: rhs_weap_pkm in the config patch for AFRF
3. add ace_overheating_allowSwapBarrel = 1; in classes: rhs_weap_mg42_base and rhs_weap_m84 in the config patch for GREF

no other changes are necessary and this would propagate to child classes in a sane manner (and create no issues that i'm aware of).

**Steps to reproduce:**
1. equip the PKM
2. place a spare barrel into your backpack
3. ACE self-interact, notice there is no swap barrel option under Equipment

**Where did the issue occur?**
- All areas.

### PR DESCRIPTION
**Pull request by PabstMirror**
Close #6653

### CODE REVIEW

File: optionals/compat_rhs_usf3/CfgWeapons.hpp [hunk 1]
```diff
@@ -70,18 +70,19 @@ class CfgWeapons {
...
     };
+    class rhs_weap_saw_base: Rifle_Base_F {
+        ACE_Overheating_allowSwapBarrel = 1;
+    };
     class rhs_weap_lmg_minimi_railed; // Rifle_Base_F - scope = private;
     class rhs_weap_m249_pip_S: rhs_weap_lmg_minimi_railed {
         ACE_RailHeightAboveBore = 4.11044;
         ACE_barrelLength = 348;
         ACE_barrelTwist = 177.8;
-        ACE_Overheating_allowSwapBarrel = 1;
```
Comment (dedmen) [inline optionals/compat_rhs_usf3/CfgWeapons.hpp]: Why remove? do they inherit from saw_base? in that case the comment after `rhs_weap_lmg_minimi_railed` should be updated.

Comment (PabstMirror) [reply optionals/compat_rhs_usf3/CfgWeapons.hpp]: inheritance is 
```
class rhs_weap_saw_base: Rifle_Base_F
class rhs_weap_lmg_minimipara: rhs_weap_saw_base
class rhs_weap_lmg_minimi_railed: rhs_weap_lmg_minimipara

//4 guns:
class rhs_weap_m249: rhs_weap_lmg_minimi_railed
class rhs_weap_m249_pip_S: rhs_weap_lmg_minimi_railed
class rhs_weap_m249_pip: rhs_weap_lmg_minimi_railed
class rhs_weap_m249_pip_L: rhs_weap_lmg_minimi_railed
```
I'll update comments
