### PR TITLE
tweaking recoil

### LINKED ISSUE #844: Recoil feedback
ACE3 Version: 3.x.x

**Mods:**
- @cba_a3
- @ace3

**Placed ACE3 Modules:**
- *NONE

**Description:**
_recoil seems way too low. especailly for the bigger calibres._

**Steps to reproduce:**
- *here we have a case of the recoil making the shooting very simplified and easy. 7.62 in full auto has very low recoil. this certainly should not be the case.

even machine guns like the navid can be used with laser accuracy while standing. with minimial mouse movement. this takes the skill away.

when i am at the range i need to focus, have my cheekweld right, pull slow on the trigger, have proper sight alianment, etc. on every shot. if not the grouping goes to hell. here its shoot, have the rifle autoreturn to almost eactly the same point, and click, and repeat. already arma 3 is very easy compared to the real experience. 

**Where did the issue occur?**
*with the current ace 3 recoil.pbo enabled

**RPT log file:**
_Add a link (pastebin.com) to the client or server RPT file._Hi
- more info follows

Love the mod. cant wait for its relase.

I know i have test an unofficial version, so i am guessing that you guys havnt finished with them yet, but at the moment, the recoil seems crazy low.

ACE 2 increased vanilla recoil for the right reasons.

but here we have a case of the recoil making the shooting very simplified and easy. 7.62 in full auto has very low recoil. this certainly should not be the case.

even machine guns like the navid can be used with laser accuracy while standing. with minimial mouse movement. this takes the skill away.

when i am at the range i need to focus, have my cheekweld right, pull slow on the trigger, have proper sight alianment, etc. on every shot. if not the grouping goes to hell. here its shoot, have the rifle autoreturn to almost eactly the same point, and click, and repeat. already arma 3 is very easy compared to the real experience. 

https://www.youtube.com/watch?v=uJQok7Wm5dU

I'd really like to see ace 3 emphasising skill required in firing through the recoil. right now the current configs make it way too easy and its doing a lot of the hard work a user should be doing - aka managing the rifle a bit more and keeping it on target..

thanks for a great mod! and running it in such a community friendly way. straight to the top of everyones books.

### PR DESCRIPTION
**Pull request by commy2**
- [x] revive tmr camshake depending on stance

### CODE REVIEW

File: addons/recoil/functions/script_component.hpp [hunk 1]
```diff
@@ -0,0 +1 @@
+#include "\z\ace\addons\overpressure\script_component.hpp"
```
Comment (KoffeinFlummi) [inline addons/recoil/functions/script_component.hpp]: boop

Comment (bux578) [inline addons/recoil/functions/script_component.hpp]: is that right?

**Comment by ulteq** [comment]
Not bad if you ask me. But it took me about half an hour to get used to it.
