### PR TITLE
Disable FCS on RHS helicopters

### LINKED ISSUE #4495: RHS: USAF AH-64D Zeroing not working correctly with ACE
**Arma 3 Version:** `1.64`
**CBA Version:** `3.1.0`
**ACE3 Version:** `3.7.0`

**Mods:**
- `@CBA_A3`
- `@ace`
- `@RHS: United States Forces` v0.4.1.1

**Description:**
- I have found out that the ACE targeting system interferes with the regular Arma 3/RHS zeroing system in such a way, that it will be impossible to get any accurate shots.
One of the way ACE intervenes, is through the UI for the zeroing. (Normally found on the top right of the UI) Whenever one uses 'tab' button to change zeroing or the manual page-up and down, the UI doesn't change to the correct number (i.e. it stays at the default position of 400m for the Apache) This, while the actual zeroing does change. 
Moreover, this messes with the AUTO-zero feature the Apache has when locking onto something. (Like your own laser) The AUTO-zero doesn't compensate for the ACE zeroing, thus making your gun 'inaccurate' and shoot short or over.

As of now, I do not know if the same problem occurs with other, similar, vehicles.

**Steps to reproduce:**
-Enable RHS USAF, ACE3 and CBA3 for Arma 3
-Use any RHS Apache helicopter and get into the gunner seat.
-Use the 'tab' button or the page up and down to use the ACE zeroing mechanism.
-See how the UI for the zeroing doesn't change.
-Test it also with AUTO-zeroing.

**Where did the issue occur?**
- Editor (Singleplayer) / Multiplayer

**Placed Modules:**
RHS: USAF AH-64D, any variant

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

### PR DESCRIPTION
**Pull request by PabstMirror**
Close #4495

### CODE REVIEW

File: optionals/compat_rhs_usf3/CfgVehicles.hpp [hunk 1]
```diff
@@ -111,6 +111,15 @@ class CfgVehicles {
             };
         };
     };
+    class AllVehicles;
+    class Air: AllVehicles {
+        class Turrets;
+    };
```
Comment (commy2) [inline optionals/compat_rhs_usf3/CfgVehicles.hpp]: replace L114 - 117 with just:
`class Air;`

**Comment by lolkij** [comment]
ACE FCS still present in the MI-24 (GSh-30)
