### PR TITLE
No Crosshair - Fix config

### LINKED ISSUE #6904: Check if ace_nocrosshair is broken
`ace_nocrosshair` might be deprecated, as changes to the game supposedly broke it.

### PR DESCRIPTION
**Pull request by Dystopian**
**When merged this pull request will:**
- fix #6904.

Current config doesn't work.

### CODE REVIEW

File: optionals/nocrosshair/CfgWeaponCursors.hpp [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    EMPTY_TEXTURE(missile);
+    EMPTY_TEXTURE(rocket);
+    EMPTY_TEXTURE(bomb);
+    EMPTY_TEXTURE(cannon);
+    EMPTY_TEXTURE(mortar);
+    EMPTY_TEXTURE(coil);
+    EMPTY_TEXTURE(laserdesignator);
+    // if these classes have empty texture the crosshair appears
+    // EMPTY_TEXTURE(cursorAim);
+    // EMPTY_TEXTURE(cursorAimOn);
```
Comment (commy2) [inline optionals/nocrosshair/CfgWeaponCursors.hpp]: Explain this please. It sounds there is an interesting story behind this.

Comment (Dystopian) [reply optionals/nocrosshair/CfgWeaponCursors.hpp]: I just added all `CfgWeaponCursors` classes and it suddenly broke my fix. So I decided to keep these classes commented if someone would want to add "missing" classes.
